### PR TITLE
Restore behavior of disableDarkMode after commit 99ad3eb regression

### PR DESCRIPTION
**Pull request by PierreAtUptale**
This change restores the functionality of `disableDarkMode` prop, whose role is to prevent the automatic use of the dark mode stylesheet if the browser has the `prefers-color-scheme` media value set to `dark`. This was initially introduced to better integrate in application that do not have a dark mode, but this feature got broken in a [subsequent change](https://github.com/hxf31891/react-gradient-color-picker/commit/99ad3eb).

See #77.

There may be a better way of merging styles than using my of `combineMultipleCssModules` utility, if anyone has any in mind.

### CODE REVIEW

**Comment by PierreAtUptale** [comment]
This seems to work when `disableDarkMode` is `true` but when it's `false | undefined` then the styling gets broken.

image

Will update.

**Comment by hxf31891** [comment]
I will take a peak at this ASAP and try and get that fixed for you. Theres has been a lot of complications bundling the styles for Next and thats limited my ability to interact with darkMode and make it accessible.

**Comment by hxf31891** [comment]
this should be fixed as of 3.0.10

**Comment by n3nikita** [comment]
Looks like it's not fixed. I'm on 3.0.10 and it doesn't seem to work.

**Pull request closed without merging**
