### PR TITLE
Optimizing drag and drop performance with translate

### PR DESCRIPTION
**Pull request by StringKe**
after:
CleanShot 2024-04-22 at 15 18 09

before:
CleanShot 2024-04-22 at 15 18 38

### CODE REVIEW

**Comment by hxf31891** [comment]
This is a great idea, will merge ASAP

**Comment by hxf31891** [comment]
@StringKe apologies for the delay here. 

I think this is a great upgrade, I just want to make sure its stable. Have you tested this thoroughly?

**Comment by StringKe** [comment]
I've tested it in my product and no other issues have arisen so far.

**Comment by hxf31891** [comment]
@StringKe i'll merge this when i get home tonight

**Comment by andoni-enriquez** [comment]
Any update on this?

**Comment by hxf31891** [comment]
@StringKe you weren't kidding, that is way better!

@andoni-enriquez I'm publish a new version as we speak.

**Pull request merged**
